name: build
on:
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Test
        run: npm test
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Lint
        run: npm run lint

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy
        run: npm run deploy

