name: deploy
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Deploy
        run: npm run deploy

